---
version: '0.8'
services:
  app:
    build:
      context: .
      dockerfile: web-director.Dockerfile

    container_name: "web-director"
    image: "haproxy:2.3"
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port

    volumes:
      - ./haproxy-config.d:/etc/haproxy/config.d
      - ./letsencrypt:/etc/letsencrypt